### PR TITLE
Brentashley patch sed params

### PR DESCRIPTION
**Pull request by brentashley**

### CODE REVIEW

**Comment by jimmypuckett** [comment]
@brentashley thanks for the PR. We will get this reviewed tomorrow.

**Comment by brentashley** [comment]
Thanks Jimmy.  FYI I was using Ubuntu 14.04 and whatever version of sed it comes with.  The sed calls failed during makeLibraries with file not found error because it thought the pattern was the filename until I made the changes.

**Comment by jimmypuckett** [comment]
@brentashley I have ran this on my mac, and it is messing up the file names.  The "-i" does...

> Edit files in-place, saving backups with the specified extension.  If a zero-length extension is given, no backup will be saved.  It is not recommended to give a zero-length extension when in-place editing files, as you risk corruption or partial content in situations where disk space is exhausted, etc.

Now all of the generated files end in ".php-e"

**Comment by brentashley** [comment]
I see.  I think the Darwin sed is a Berkeley descendent and behaves differently from the GNU/Linux sed which is descended from AT&T/SysV (ps is different between the two as well for instance).  I have both Mac and Ubuntu so I will try a few syntaxes to see what works across both and get back to you.

**Comment by brentashley** [comment]
FYI man for Linux sed says this about -i:

       -i[SUFFIX], --in-place[=SUFFIX]
              edit files in place (makes backup if SUFFIX supplied)

and this about syntax showing that script will be taken positionally if no -e specified:

SYNOPSIS
       sed [OPTION]... {script-only-if-no-other-script} [input-file]...

**Comment by brentashley** [comment]
These two syntaxes work with both Ubuntu and Mac sed:

    sed -i"" -e "s/this/that/g" filename.ext
    sed -ie "s/this/that/g" filename.ext

i.e., no space between -i and the quotes, or both i and e in a compound switch, forcing it to recognize it as meaning no backup

Rather than re-PR-ing, I'll leave you to decide which syntax to use.

Thanks for the library (and generator).  We'll not be doing our integration for a while so will likely wait for REST stuff to be all in place before diving in too deep.

**Comment by jimmypuckett** [comment]
It is so nice to have someone give some back!  Thanks for taking the time to find the right syntax for both systems.

Let me do a little digging too & bounce it off of the team a little.  If this is not holding you up, I'd like to do it tomorrow?

I am not sure if you saw that we have started a feature branch for the REST API?  I have been working with CW & they got me the SWAGGER json definitions ahead of release, so we generated up a new version (no test yet).  We are having a few issues with their endpoints as defined in the file, so it is not usable yet.  We are hoping that after IT Nation (next week), that we should get some traction on them.

Talk soon.

**Comment by brentashley** [comment]
Thanks, Jimmy.

Yes, I'm in no hurry, tomorrow is fine.  I had indeed noted the REST
branch.  We are at an early stage with our CW implementation so I'm just
scouting out solutions and kicking tires right now, but I had this sed
hiccup while testing the generation script and figured I should share the
fix.  I will point our dev team to your repo for when they get up to speed.

 - Brent -

Brent Ashley
Assoc VP Infrastructure Architecture
ControlCase.com
Compliance as a Service
bashley@controlcase.com

**Comment by jimmypuckett** [comment]
OK, I am thinking that ```sed -i"" -e "s/this/that/g" filename.ext``` is the is more readable to remind use that the empty value for the ```-i```.  If you will update your PR to that line, then we will merge it.

Thanks again for doing this!

**Comment by brentashley** [comment]
OK I think that did it.

**Comment by jimmypuckett** [comment]
@brentashley, so I pulled down your new code & I still got files that end in .php-e, so I tried the other option that you gave & it gave me files that end in .phpe.  I did some digging & it looks like here is no good way to use ```sed -i``` in a portable manner...

http://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux
http://unix.stackexchange.com/questions/92895/how-to-achieve-portability-with-sed-i-in-place-editing

From my reading there are the following options...

1. Detect the OS & use the space for BSD or no space with others
2. Let sed generate the backup files & then delete them
3. Switch the way that we are doing the inlace edits

Do you have an opinion about the these options? Do you have a different solution?

**Comment by brentashley** [comment]
Funny, apparently all the time it had been generating the backup file for me too but I simply missed it on the mac while I was paying close attention to the change in file content of the original file.  Doh!  I think it's easiest just to make the backup suffix unique enough and then delete the backup.  A 4th option is adding a switch and documenting that linux users need to use -L or something of the sort but it's better to not make them have to think.

**Comment by jimmypuckett** [comment]
Ya, I think that letting the backup generate & blowing it away is the easiest.  You have put so much effort into this that you can either update your PR again or just abandon it & we will get the delete in there.  Just let me know what you want us to do.

**Comment by brentashley** [comment]
Thanks, I deleted the branch.  Glad we got it worked out in the end.  Silly little issue but a good way to get acquainted.  I'll keep my eye on the project.

**Pull request closed without merging**
